apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "temporal-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "temporal-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "temporal-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.manager.args | nindent 8 }}
        command:
        - /manager
        image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - name: webhook-server
          {{- if .Values.webhook.containerPort }}
          containerPort: {{ .Values.webhook.containerPort }}
          {{- else }}
          containerPort: 9443
          {{- end }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.manager.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: true
      {{- if .Values.webhook.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      serviceAccountName: {{ include "temporal-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      nodeSelector: {{ toYaml .Values.manager.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.manager.tolerations | nindent 8 }}
