site_name: Temporal Operator
site_url: https://alexandrevilain.github.io/temporal-operator/
repo_url: https://github.com/alexandrevilain/temporal-operator
repo_name: alexandrevilain/temporal-operator
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home:
    - Overview: index.md
    - getting-started.md
  - Features:
    - Dynamic config: features/dynamic-config.md
    - Archival: features/archival.md
    - Temporal UI: features/temporal-ui.md
    - Admin Tools: features/admin-tools.md
    - mTLS:
      - Using Cert-Manager: features/mtls/cert-manager.md
      - Using Istio: features/mtls/istio.md
      - Using Linkerd: features/mtls/linkerd.md
    - Monitoring:
      - Using prometheus-operator: features/monitoring/prometheus-operator.md
      - Using prometheus: features/monitoring/prometheus.md
    - Overrides: features/overrides.md
    - ArgoCD: features/argocd.md
  - API:
    - v1beta1: api/v1beta1.md
  - Contributing:
    - contributing/local-development.md
    - contributing/publish-release.md
