---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-temporal-io-v1beta1-temporalcluster
  failurePolicy: Fail
  name: mtemporalc.kb.io
  rules:
  - apiGroups:
    - temporal.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temporalclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-temporal-io-v1beta1-temporalcluster
  failurePolicy: Fail
  name: vtemporalc.kb.io
  rules:
  - apiGroups:
    - temporal.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temporalclusters
  sideEffects: None
