manager:
  # -- Arguments to be passed to the controller manager container.
  args:
  - --leader-elect
  # -- Security context for the controller manager container.
  containerSecurityContext:
    # -- Disallow privilege escalation for the container.
    allowPrivilegeEscalation: false
  image:
    # -- Docker image repository for the controller manager container.
    repository: ghcr.io/alexandrevilain/temporal-operator
    # Will use AppVersion as the image tag by default
    # tag: v0.0.0
  resources:
    # -- Resources limits for the controller manager container.
    limits:
      cpu: 500m
      memory: 128Mi
    # -- Resources requests for the controller manager container.
    requests:
      cpu: 10m
      memory: 64Mi
  # -- Number of controller manager replicas to deploy.
  replicas: 1
  # -- Service account settings for the controller manager container.
  serviceAccount:
    annotations: {}
  nodeSelector: {}
  tolerations: []

webhook:
  # -- Service ports settings for the webhook server.
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  # -- Service type for the webhook server.
  type: ClusterIP
  # -- Certificate manager settings for the webhook server.
  certManager:
    # -- Webhook certificate configuration using cert-manager. 
    certificate:
      # -- Enabled defines if cert-manager should be used to manage the webhook certificate.
      enabled: true
      # -- Defines if cert-manager should use self-signed issuer or custom issuer.
      useCustomIssuer: false
      # -- Issuer references if you want to use custom issuer
      # In other case will be used selfSigned issuer.
      issuerRef: {}
  # -- The port that the webhook listens on.
  containerPort: 9443
  # -- Set to true if the webhook should be started in hostNetwork mode.
  # This is useful in managed clusters (e.g. AWS EKS) with custom CNI (such as Calico),
  # where the control-plane cannot reach pods' IP CIDR and admission webhooks are not working.
  # `webhook.containerPort` should be adapted in case it conflicts with the host network.
  hostNetwork: false

# -- Image pull secrets for accessing private image repositories.
imagePullSecrets: []
# -- Domain for the cluster.
kubernetesClusterDomain: cluster.local
