# permissions for end users to edit temporalnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporalnamespace-editor-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalnamespaces/status
  verbs:
  - get
