# permissions for end users to view temporalnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporalnamespace-viewer-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalnamespaces/status
  verbs:
  - get
