apiVersion: temporal.io/v1beta1
kind: Cluster
metadata:
  name: prod
  namespace: demo
spec:
  version: 1.17.0
  numHistoryShards: 1
  jobTtlSecondsAfterFinished: 300 
  persistence:
    defaultStore: default
    visibilityStore: visibility
    advancedVisibilityStore: es
  datastores:
    - name: default
      sql:
        user: temporal
        pluginName: postgres
        databaseName: temporal
        connectAddr: postgres.demo.svc.cluster.local:5432
        connectProtocol: tcp
      passwordSecretRef:
        name: postgres-password
        key: PASSWORD
    - name: visibility
      sql:
        user: temporal
        pluginName: postgres
        databaseName: temporal_visibility
        connectAddr: postgres.demo.svc.cluster.local:5432
        connectProtocol: tcp
      passwordSecretRef:
        name: postgres-password
        key: PASSWORD
    - name: es
      elasticsearch:
        version: v7
        username: admin
        url: http://opensearch-cluster-master.demo:9200
        indices:
          visibility: temporal_visibility_v1_dev
      passwordSecretRef:
        name: es-password
        key: PASSWORD
  ui:
    enabled: true
  admintools:
    enabled: true