apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporal-system
namePrefix: temporal-operator-

resources:
- ../rbac
- ../manager

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: controller-manager
    namespace: system
  spec:
    template:
      spec:
        containers:
        - name: manager
          image: temporal-operator:latest
          imagePullPolicy: IfNotPresent